# Generated by Django 4.2.24 on 2025-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('Address', models.CharField(max_length=50, unique=True)),
                ('Phone', models.IntegerField(default=0)),
            ],
        ),
    ]
