# Generated by Django 4.2.24 on 2025-09-17 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(null=True)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst_amount', models.IntegerField(default=0)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customers')),
                ('product_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
